// Generates src/Nuraherbex.UI/Components/Ui/LucideIcons.g.cs from the lucide-react icons the React storefront actually uses.
// Run from the repo root:  node blazor/tools/gen-icons.cjs
// Extra icons can be requested:  node blazor/tools/gen-icons.cjs Heart Package
const fs = require('fs');
const path = require('path');

const root = path.resolve(__dirname, '..', '..');
const React = require(path.join(root, 'node_modules', 'react'));
const { renderToStaticMarkup } = require(path.join(root, 'node_modules', 'react-dom', 'server'));
const lucide = require(path.join(root, 'node_modules', 'lucide-react'));

function walk(dir, out = []) {
  for (const e of fs.readdirSync(dir, { withFileTypes: true })) {
    const p = path.join(dir, e.name);
    if (e.isDirectory()) walk(p, out);
    else if (/\.(jsx?|tsx?)$/.test(e.name)) out.push(p);
  }
  return out;
}

const names = new Set(process.argv.slice(2));
// Extra icons requested by Blazor-only UI (not present in the React source) live in blazor/tools/extra-icons.txt.
const extraFile = path.join(__dirname, 'extra-icons.txt');
if (fs.existsSync(extraFile)) fs.readFileSync(extraFile, 'utf8').split(/\s+/).filter(Boolean).forEach((n) => names.add(n));
const re = /import\s*\{([^}]+)\}\s*from\s*['"]lucide-react['"]/g;
for (const f of walk(path.join(root, 'src'))) {
  const src = fs.readFileSync(f, 'utf8');
  let m;
  while ((m = re.exec(src))) {
    m[1].split(',').map((s) => s.trim().split(/\s+as\s+/)[0]).filter(Boolean).forEach((n) => names.add(n));
  }
}

const entries = [];
const missing = [];
for (const name of [...names].sort()) {
  const Comp = lucide[name];
  if (!Comp) { missing.push(name); continue; }
  const html = renderToStaticMarkup(React.createElement(Comp, { size: 24 }));
  const inner = html.replace(/^<svg[^>]*>/, '').replace(/<\/svg>$/, '');
  entries.push([name, inner]);
}

const esc = (s) => s.replace(/\\/g, '\\\\').replace(/"/g, '""');
let cs = `// <auto-generated> by blazor/tools/gen-icons.cjs — do not edit. </auto-generated>\nnamespace Nuraherbex.UI.Components.Ui;\n\npublic static class LucideIcons\n{\n    public static readonly Dictionary<string, string> Paths = new(StringComparer.OrdinalIgnoreCase)\n    {\n`;
for (const [name, inner] of entries) cs += `        ["${name}"] = @"${esc(inner)}",\n`;
cs += `    };\n}\n`;

const outDir = path.join(root, 'blazor', 'src', 'Nuraherbex.UI', 'Components', 'Ui');
fs.mkdirSync(outDir, { recursive: true });
fs.writeFileSync(path.join(outDir, 'LucideIcons.g.cs'), cs, 'utf8');
console.log(`Generated ${entries.length} icons.${missing.length ? ' Missing: ' + missing.join(', ') : ''}`);
console.log(entries.map((e) => e[0]).join(' '));
